### ISSUE TITLE
'_SpecialForm' object has no attribute 'split'

### ISSUE THREAD

**Issue by roachsinai** [mengfu188/simple-mediapipe#1]
Get error when run `python test/demo_run.py simple_mediapipe/graphs/sample3.pbtxt`.

Python version: 3.8.13

Error info:

```
[I 220923 11:24:07 demo_run:37] node {
      calculator: "ProducerCalculator"
      output_stream: "data"
    }
    node {
      calculator: "ConsumerCalculator"
      input_stream: "data"
    }

[I 220923 11:24:07 stream:38] stream <OUTPUT_STREAM:"data", current queue size is 0> add downstream <INPUT_STREAM:"data", current queue size is 0>
[I 220923 11:24:07 collection:14] collection add OUTPUT_STREAM:"data", current queue size is 0, data
[I 220923 11:24:07 stream:38] stream <INPUT_STREAM:"data", current queue size is 0> add downstream <<bound method CalculatorNode.input_stream_listener of ConsumerCalculator_1, inputs: [], outputs: []>>
[I 220923 11:24:07 collection:14] collection add INPUT_STREAM:"data", current queue size is 0, data
[I 220923 11:24:07 graph:285] initialize graph success ^_^
[I 220923 11:24:07 scheduler:115] starting scheduler
[I 220923 11:24:08 packet:26] create typing.Union[NoneType, ForwardRef('StreamType')] typing.Union[NoneType, str]
[E 220923 11:24:08 calculator:94] '_SpecialForm' object has no attribute 'split'
    Traceback (most recent call last):
      File "E:\code\Git\mediapipe_repo\simple-mediapipe\simple_mediapipe\calculator.py", line 87, in run
        self.calculator_base.process(self._default_context)
      File "E:\code\Git\mediapipe_repo\simple-mediapipe\simple_mediapipe\calculators\core\__init__.py", line 52, in process
        packet = Packet(data={'id':self.id})
      File "E:\code\Git\mediapipe_repo\simple-mediapipe\simple_mediapipe\packet.py", line 29, in __init__
        self.tag, self.index, self.name = parse_tag_index_name(tag_index_name)
      File "E:\code\Git\mediapipe_repo\simple-mediapipe\simple_mediapipe\tool\__init__.py", line 14, in parse_tag_index_name
        parts = tag_index_name.split(':')
      File "C:\Users\xq\miniconda3\envs\simp_mp\lib\typing.py", line 759, in __getattr__
        return getattr(self.__origin__, attr)
    AttributeError: '_SpecialForm' object has no attribute 'split'
```

Thanks!

**Comment by fanqie03** [comment]
Fix this problem

**Comment by roachsinai** [comment]
可以了，感谢！
